### ISSUE TITLE
Max hangs unresponsive on Windows

### ISSUE THREAD

**Issue by Pezz89** [AlexHarker/FrameLib#62] opened 2020-07-16 17:21 UTC
On commit: https://github.com/AlexHarker/FrameLib/commit/8bd586808530daab5a03472d6e41fa47b756090b (time-smoothing-decisions branch)
Build targeting Debug 64x from cleaned project, Adding any combination of fl objects such as those illustrated below locks up Max, requiring it to be killed by the task manager. Max will lock up instantly if loading from a saved file, or may need the audio turning off if objects were added after the audio was turned on (Max seems to become unresponsive when any significant audio event occurs)

![Capture](https://user-images.githubusercontent.com/10585430/87701516-04ebc600-c790-11ea-9615-dbf19c0643b7.PNG)

Building produces a single error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open source file: '..\..\..\FrameLib_Max_Objects\Time_Smoothing\fl.ewmsd~.cpp': No such file or directory	fl.ewmsd~	C:\Users\BP\Work\EHS\EHS_MSc_projects\GJ\GJ_Experiment\FrameLib2\FrameLib\Projects\Visual_Studio\03_Max_Objects\c1xx	1	

```

When max locks up the following outputs appear when monitoring through attached Visual Studio debugger. There is no stack trace however as the program never actually crashes, just perpetually hangs (unless there is some way or retrieving a stack track from the point at which Max quit when killed by the task manager which I am unaware of?)

```
'Max.exe' (Win32): Unloaded 'C:\Program Files\Cycling '74\Max 8\resources\externals\max\button.mxe64'
'Max.exe' (Win32): Loaded 'C:\Program Files\Cycling '74\Max 8\resources\externals\max\button.mxe64'. Cannot find or open the PDB file.
'Max.exe' (Win32): Loaded 'C:\Users\BP\Work\EHS\EHS_MSc_projects\GJ\GJ_Experiment\FrameLib2\FrameLib\build\Debug_x64\fl.tomax~.mxe64'. Symbols loaded.
'Max.exe' (Win32): Unloaded 'C:\Users\BP\Work\EHS\EHS_MSc_projects\GJ\GJ_Experiment\FrameLib2\FrameLib\build\Debug_x64\fl.tomax~.mxe64'
'Max.exe' (Win32): Loaded 'C:\Users\BP\Work\EHS\EHS_MSc_projects\GJ\GJ_Experiment\FrameLib2\FrameLib\build\Debug_x64\fl.tomax~.mxe64'. Symbols loaded.
The thread 0x16d4 has exited with code 0 (0x0).
The thread 0x12a0 has exited with code 0 (0x0).
The thread 0x43cc has exited with code 0 (0x0).
```
EDIT: When killed by the task manager there are zombie max processes left behind that it is impossible to kill through any method I know of for killing processes. This is perhaps why there is no stack trace, as the program never finishes? I'm not sure, my understanding of Windows OS is limited.
![Capture](https://user-images.githubusercontent.com/10585430/87702534-70826300-c791-11ea-917f-865a273101fc.PNG)

**Comment by AlexHarker** [comment] 2020-08-16 13:32
That branch is currently merged into object-review.

I've just built the branch with Debug x64 config and I can't reproduce the bug. Can you either try again (building is also now fixed) or provide any further info on this?

**Comment by AlexHarker** [comment] 2020-08-16 14:36
OK - I took another look and I got hangs when deleting objects, but not when turning audio on, which I *suspect* may have been the bug you were seeing. That bug is now fixed (a1626ff2caeb9afb8aadc5c63ef51aeb2ebfe8ea), although it looks like the windows build (which includes optional multi-threading on the object-review branch) may suffer from high CPU overhead, and./or poor audio performance, which is likely a longer investigation.

 It would be great if you could confirm that you no longer experience this issue and/or if you see the poor performance by pulling object-review and building there. If necessary I can also provide a build to test.

**Comment by AlexHarker** [comment] 2020-08-16 16:01
Final update before I wait for a test - looks like low performance may have been on debug builds only, which is to be expected. Have pushed some more changes that should result in a successful release build with no errors or warnings, which seems to be perfuming fine. @Pezz89 - if you could confirm if you are still seeing an issue at your convenience then I'll look at investigating further, or closing the issue as appropriate.

**Comment by Pezz89** [comment] 2020-08-17 12:47
The solution now appears to build successfully, and simple Max patches don't appear to be hanging anymore so it appears on the surface that the problem is fixed! I am getting the following warning when building for debug: `Warning	LNK4075	ignoring '/INCREMENTAL' due to '/LTCG' specification` - I don't know quite what this means but doesn't seem to cause any issues.
I'll do some more in depth testing over the next few days and begin merging with my development branch to confirm but for the time being it looks like everything's working well, thanks!

**Closed** 2020-08-17 12:47 UTC

**Comment by AlexHarker** [comment] 2020-08-17 15:16
Yes - I'm aware of the linker warning, but it is harmless - it only affects debug builds, and I don't do much debugging on windows, but at some point I'll try to clean this up - great that this fixed it!
