### ISSUE TITLE
@rt 0 does not seem to work on Windows

### ISSUE THREAD

**Issue by balintlaczko** [AlexHarker/FrameLib#80] opened 2021-04-27 19:55 UTC
Hey there, and thanks for this awesome toolbox! I am digging myself through the tutorials, and as I reached the NRT section, I noticed, that none of the examples work (ie. produce anything in the output buffers). I tried to test it in a new patch, but it does not seem to work there either:

![image](https://user-images.githubusercontent.com/45127463/116304347-c2d1c500-a7a2-11eb-8911-f10064c92513.png)

Anyone had this issue before? Am I missing something perhaps? Quite an fl.noob here...
I am using the Windows build from the release version.

**Comment by AlexHarker** [comment] 2021-04-27 21:11
Thanks for the report. The windows build is unfortunately a little less tested, so I'm not sure (yet) what is going on here. The context detection and communication system is a little bit involved under the hood, and so my guess is that some step of that may be failing. 

I will try to find some time to test this in the debugger when I can.

**Comment by AlexHarker** [comment] 2021-04-28 09:12
One thing that you could easily check, however, is whether the ft.sink~ object appears to be in the correct context (or not). To do this please open a NRT patch (or the one you posted), click on the button that processes and then select fl.sink~ and via the inspector. The @rt and @id attributes should be set as for the scheduler (the fl.interval~ object). If you could let me know if this is the case or not that would give me a better idea of where I might be looking.

**Comment by AlexHarker** [comment] 2021-04-28 12:30
OK - issue confirmed on my windows build so this is a build, rather than a hardware issue (I'm running on Mac hardware). The id and rt attributes are being set correctly, so it looks like something else is going on. I will investigate further against the latest version of main and with a debug build.

**Comment by AlexHarker** [comment] 2021-04-28 13:31
This was a rather surprising method signature error, that for some reason the Mac compiler was dealing with in a way that worked (when this certainly isn't guaranteed but I can see how it might have happened), but the windows compiler was not. 
Now I've corrected the method to use a pointer (not an object) it fixes things on windows and still works on Mac.

It is fixed in add270412bb78169c290038db986f1d359d06f7d

Thanks for reporting - very much appreciated to be able to for these bugs!

Let me know if you are keen to get a build, as the fix is in the code only at the moment.

**Closed by AlexHarker** 2021-04-28 13:31 UTC

**Comment by balintlaczko** [comment] 2021-04-28 15:12
Oh, wow, this is great, you are so fast! I would really appreciate if I could get a build with this, yes! :)))

**Comment by AlexHarker** [comment] 2021-04-28 15:23
I've put a win 64 bit version of the externals only here:

https://drive.google.com/file/d/1CaDM8F6XtRUIyklj8_m-0Va0KVtotZ6Q/view?usp=sharing

Let me know if that works for you.

**Comment by balintlaczko** [comment] 2021-04-28 16:19
I can confirm that NRT works as expected with the new externals! Thanks so much!
